M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu22.04.1} date Tue 12 Dec 2023 12:02:22 PM EET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-12T12:02:22+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X5.0674Y-4.6597
X5.295Y-4.6597
T2
X5.2116Y-3.7959
X5.3297Y-3.7959
T0
M30
